openapi: 3.1.0
info:
  version: 1.0.0
  title: API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of REST API
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Categories
    description: Categories operations.
  - name: Areas
    description: Areas operations
  - name: Ingredients
    description: Ingridients operations
  - name: Testimonials
    description: Testimonials operations
servers:
  - url: http://0.0.0.0:3000/api
paths:
  # AUTH
  /auth/register:
    post:
      $ref: ./../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ./../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ./../swagger/paths/auth/logout/post.yaml
  # USERS
  /users/current:
    get:
      $ref: ./../swagger/paths/users/current/get.yaml
  /users/{id}:
    get:
      $ref: ./../swagger/paths/users/{id}/get.yaml
  /users/avatars:
    patch:
      $ref: ./../swagger/paths/users/avatars/patch.yaml
  /users/followers:
    get:
      $ref: ./../swagger/paths/users/followers/get.yaml
  /users/following:
    get:
      $ref: ./../swagger/paths/users/following/get.yaml
    patch:
      $ref: ./../swagger/paths/users/following/patch.yaml
    delete:
      $ref: ./../swagger/paths/users/following/delete.yaml
  # CATEGORIES
  /categories:
    get:
      $ref: ./../swagger/paths/categories/get.yaml
  # AREAS
  /areas:
    get:
      $ref: ./../swagger/paths/areas/get.yaml
  # INGRIDIENTS
  /ingredients:
    get:
      $ref: ./../swagger/paths/ingredients/get.yaml
  # TESTIMONIALS
  /testimonials:
    get:
      $ref: ./../swagger/paths/testimonials/get.yaml
  # RECIPES
  /recipes/search:
    get:
      $ref: ./../swagger/paths/recipes/search/get.yaml
  /recipes:
    get:
      $ref: ./../swagger/paths/recipes/get.yaml
  /recipes/{id}:
    get:
      $ref: ./../swagger/paths/recipes/{id}/get.yaml
    post:
      $ref: ./../swagger/paths/recipes/{id}/post.yaml
    delete:
      $ref: ./../swagger/paths/recipes/{id}/delete.yaml
  /recipes/top:
    get:
      $ref: ./../swagger/paths/recipes/top/get.yaml
  /recipes/favorites/{id}:
    patch:
      $ref: ./../swagger/paths/recipes/favorites/{id}/patch.yaml
    delete:
      $ref: ./../swagger/paths/recipes/favorites/{id}/delete.yaml
  /recipes/favorites:
    get:
      $ref: ./../swagger/paths/recipes/favorites/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
